// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/_fragments": {
    params: {};
  };
  "/_fragments/:zon": {
    params: {
      "zon": string;
    };
  };
  "/_fragments/:zon/*": {
    params: {
      "zon": string;
      "*": string;
    };
  };
  "/:zon": {
    params: {
      "zon": string;
    };
  };
  "/:zon/*": {
    params: {
      "zon": string;
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/_fragments" | "/_fragments/:zon" | "/_fragments/:zon/*" | "/:zon" | "/:zon/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/fragments.tsx": {
    id: "fragments-home";
    page: "/_fragments";
  } | {
    id: "fragments-zon";
    page: "/_fragments/:zon";
  } | {
    id: "fragments-file";
    page: "/_fragments/:zon/*";
  };
  "routes/zon.tsx": {
    id: "routes/zon";
    page: "/:zon";
  };
  "routes/file.tsx": {
    id: "routes/file";
    page: "/:zon/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "fragments-home": typeof import("./app/routes/fragments.tsx");
  "fragments-zon": typeof import("./app/routes/fragments.tsx");
  "fragments-file": typeof import("./app/routes/fragments.tsx");
  "routes/zon": typeof import("./app/routes/zon.tsx");
  "routes/file": typeof import("./app/routes/file.tsx");
};